version: "2.1"

services:
  nginx:
    volumes:
      - ${BACKEND_PATH}/static:/usr/share/nginx/html/
      - ${BACKEND_PATH}/media:/usr/share/nginx/html/media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config:/etc/nginx/config
      - ./docker/nginx/dev_conf.d:/etc/nginx/conf.d

  web:
    command: >
      bash -c  "rm -rf static/* &&                              # remove old static
                python manage.py collectstatic --noinput &&     # collect admin static in static folder
                python manage.py migrate &&                     # apply migrations
                gunicorn ${DJANGO_APPNAME}.wsgi:application -b 0.0.0.0:8000 --workers=${WSGI_WORKERS} --log-level debug --reload"
    volumes:
      - ${BACKEND_PATH}:/code
    environment:
      REDIS_HOST: redis
      ENV: dev

  redis:
    volumes:
      - redis_data:/redis_data

volumes:
  redis_data: